### PR TITLE
Add empty theme

### PR DESCRIPTION
**Pull request by sfc-gh-jlai**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #DOC-845

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

This change adds an empty theme and specifies it as the theme to use when producing documentation. With the [Snowpark Python API reference documentation being newly integrated into Snowflake's documentation as a first-class citizen](https://docs.snowflake.com/developer-guide/snowpark/reference/python/latest/index), generating the documentation using an empty template is a requirement for embedding.

### CODE REVIEW

**Comment by sfc-gh-jlai** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-jlai** [comment]
recheck

**Review by sfc-gh-sfan — APPROVED** [review]

**Comment by sfc-gh-sfan** [comment]
@sfc-gh-mkeller (oncall): could you take a look at the tests? I think we just need a test PR for it.

**Comment by sfc-gh-jlai** [comment]
@sfc-gh-sfan @sfc-gh-mkeller I've triggered another build and the original issue about the Changelog check has cleared, but a whole new collection of failures has been introduced. Could I get some help understanding how to resolve these? Again, this change doesn't have any code-level impact so I'm surprised to see anything breaking here.

**Comment by sfc-gh-mappleton** [comment]
> @sfc-gh-sfan @sfc-gh-mkeller I've triggered another build and the original issue about the Changelog check has cleared, but a whole new collection of failures has been introduced. Could I get some help understanding how to resolve these? Again, this change doesn't have any code-level impact so I'm surprised to see anything breaking here.

@sfc-gh-sfan @sfc-gh-mkeller any update here? the docs team we need this change in to publish the Snowpark docs

**Pull request merged**
