### PR TITLE
mark xfail on if_not_exist tests 

### PR DESCRIPTION
**Pull request by sfc-gh-aalam**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Tests that are testing `if_not_exists` show flaky behavior and fail error messages like with `Unknown function TEST_SP_IF_NOT_EXISTS_ADD` on first invocation of sp/udf after being registered with `if_not_exists=True`. Updating the first isntance of registration with `replace=True` instead of `if_not_exists` to test whether it fixes the flakiness.

### CODE REVIEW

**Comment by sfc-gh-stan** [comment]
🤔  Why should changing it to `replace` fix this issue?

**Review by sfc-gh-sfan — COMMENTED** [review]
I'm also confused why this would fix the issue 🤔

**Comment by sfc-gh-aalam** [comment]
> 🤔 Why would changing it to `replace` fix this issue?

Let me do more research to find a good explanation for this.

**Comment by sfc-gh-aalam** [comment]
A bug is identified when creating temp stored procs with if not exists. https://snowflakecomputing.atlassian.net/browse/SNOW-757054

**Comment by sfc-gh-stan** [comment]
Thank you for investigating! I see the bug fix has been assigned. Since the tests are for `if exists`, I don't think we should fix it by using `replace`. 🤔 Let's either quarantine it with `pytest.mark.xfail(strict=False, reason="SNOW-xxxx")` or just skip it?

**Comment by sfc-gh-aalam** [comment]
> Thank you for investigating! I see the bug fix has been assigned. Since the tests are for `if exists`, I don't think we should fix it by using `replace`. 🤔 Let's either quarantine it with `pytest.mark.xfail(strict=False, reason="SNOW-xxxx")` or just skip it?

You are right. Marking `xfail` seems like the right move

**Review by sfc-gh-stan — APPROVED** [review]

**Pull request merged**
