### PR TITLE
[SNOW-1478924]: Ensure `__getitem__` on DataFrameGroupBy returns SeriesGroupBy when appropriate even if `as_index=False`

### PR DESCRIPTION
**Pull request by sfc-gh-rdurrani**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1478924

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.
   - [ ] I acknowledge that I have ensured my changes to be thread-safe. Follow the link for more information: [Thread-safe Developer Guidelines](https://docs.google.com/document/d/162d_i4zZ2AfcGRXojj0jByt8EUq-DrSHPPnTa4QvwbA/edit#bookmark=id.e82u4nekq80k)

3. Please describe how your code solves the related issue.

Ensure that getitem on a DataFrameGroupBy returns a SeriesGroupBy if only one column is indexed, even if `as_index=False`.

### CODE REVIEW

**Review by sfc-gh-nkrishna — COMMENTED** [review]
Can we add tests for this?

**Comment by sfc-gh-nkrishna** [comment]
> > Can we add tests for this?
> 
> I think there are already tests for this? Because in a lot of the groupby tests, we have a **getitem** test, so that checks that this works correctly. Would you like me to add some tests that check the types of SeriesGroupBy vs. DataFrameGroupBy?

Yeah in general I think it would be helpful to have an associated test (an isinstance check sounds good to me) whenever there is a bug fix

**Review by sfc-gh-nkrishna — APPROVED** [review]
LGTM!

**Review by sfc-gh-lmukhopadhyay — APPROVED** [review]
LGTM!

**Pull request merged**
