### PR TITLE
SNOW-817445 fix pre-commit tests

### PR DESCRIPTION
**Pull request by sfc-gh-aalam**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #NNNN

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Please write a short description of how your code change solves the related issue.

### CODE REVIEW

**Comment by sfc-gh-aalam** [comment]
pre-commit run: https://ci-dev-142.int.snowflakecomputing.com/job/PythonStoredProcBuildPrecommitTest/441/

**Comment by sfc-gh-aalam** [comment]
Successful pre-commit run: https://ci-dev-133.int.snowflakecomputing.com/job/RT-Precommit/12720/

**Review by sfc-gh-sfan — APPROVED** [review]
I'm a bit confused about why our merge gate is not impacted. Is it because for precommit test we are testing against changes that are not in prod yet?

**Comment by sfc-gh-aalam** [comment]
> I'm a bit confused about why our merge gate is not impacted. Is it because for precommit test we are testing against changes that are not in prod yet?

There is a bug which only affects string types in reg environment: https://snowflakecomputing.atlassian.net/browse/SNOW-815544

**Pull request merged**
