### PR TITLE
SNOW-1320543 Update modin class paths

### PR DESCRIPTION
**Pull request by sfc-gh-vbudati**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-1320543

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Change modin classpaths from `snowflake.snowpark.modin.pandas.<>` to `modin.pandas.<>`.

To see the changes locally run:
```
cd docs
make clean; make html
open -a "Google Chrome" build/html/index.html
```

To see the docs in a nice format, change the variable `html_theme` in `docs/source/conf.py:70` to `"alabaster"`.

### CODE REVIEW

**Review by sfc-gh-nkrishna — APPROVED** [review]
LGTM! What's the downside of permanently leaving it as "alabaster" so much nicer lol

**Comment by sfc-gh-vbudati** [comment]
@sfc-gh-nkrishna I have no idea lol. There was a comment in the ol' snowpandas fork that mentioned "switching back to the empty theme once merged back". Just following orders, although it is a very nice theme. 😆

**Review by sfc-gh-joshi — APPROVED** [review]
LGTM, thanks for figuring this out!

**Review by sfc-gh-aling — APPROVED** [review]
I'm not familiar with doc generation, but you should be able to verify your change through the doc in the generated artifacts:  https://github.com/snowflakedb/snowpark-python/actions/runs/8902614293?pr=1469#artifacts

**Comment by sfc-gh-vbudati** [comment]
@sfc-gh-joshi @sfc-gh-nkrishna I was double checking the docs generated by this code:
on the pages for general functions (anything in `snowflake.snowpark.modin.pandas.general`/`general_functions.rst`) the class path displayed below the function name is still `snowflake.snowpark.modin.pandas.melt` instead of `modin.pandas.melt`. This is also the case for the class pages of Series and DataFrame where the full classpath is displayed.

I'm not sure how to fix this, not sure if this is worth fixing. All the other APIs are displayed correctly. The headings are displayed correctly - this is just the module line that has the "full" classpath present in the aforementioned files. 

What do you think?

Take a look at the docs for:
- snowflake.snowpark.modin.pandas.Series.html
- snowflake.snowpark.modin.pandas.general.melt.html
- snowflake.snowpark.modin.pandas.DataFrame.html
versus the expected (any other file that's not in general).

**Comment by sfc-gh-nkrishna** [comment]
> @sfc-gh-joshi @sfc-gh-nkrishna I was double checking the docs generated by this code: on the pages for general functions (anything in `snowflake.snowpark.modin.pandas.general`/`general_functions.rst`) the class path displayed below the function name is still `snowflake.snowpark.modin.pandas.melt` instead of `modin.pandas.melt`. This is also the case for the class pages of Series and DataFrame where the full classpath is displayed.
> 
> I'm not sure how to fix this, not sure if this is worth fixing. All the other APIs are displayed correctly. The headings are displayed correctly - this is just the module line that has the "full" classpath present in the aforementioned files.
> 
> What do you think?
> 
> Take a look at the docs for:
> 
> * snowflake.snowpark.modin.pandas.Series.html
> * snowflake.snowpark.modin.pandas.general.melt.html
> * snowflake.snowpark.modin.pandas.DataFrame.html
>   versus the expected (any other file that's not in general).

@sfc-gh-vbudati This is behavior we should run by Sri/Brenan I think. Maybe worth a post on the channel?

**Pull request merged**
