### PR TITLE
Fix of to_pandas() when having integer column with null values

### PR DESCRIPTION
**Pull request by frederiksteiner**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes [SNOW-1026241 ](https://github.com/snowflakedb/snowpark-python/issues/1229)

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   When there is a NaN value in the column, it does not try to cast it to integer but keeps it as float64

### CODE REVIEW

**Comment by sfc-gh-aalam** [comment]
recheck

**Review by sfc-gh-aalam — APPROVED** [review]

**Comment by frederiksteiner** [comment]
recheck

**Comment by frederiksteiner** [comment]
I hope I did it properly

**Comment by frederiksteinerSBB** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by frederiksteinerSBB** [comment]
recheck

**Review by sfc-gh-stan — APPROVED** [review]
The code changes LGTM ~but I think we should include this in 1.13.0 minor release instead of doing a separate patch release.~ [Update]: Confirmed with Afroz we will release 1.12.1

**Pull request merged**
