### PR TITLE
SNOW-1018248: Add support for asof join in snowpark

### PR DESCRIPTION
**Pull request by sfc-gh-aalam**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #SNOW-1018248

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Add ASOF join support in snowpark python.

### CODE REVIEW

**Comment by sfc-gh-aalam** [comment]
https://ci-dev-142.int.snowflakecomputing.com/job/PythonStoredProcBuildPrecommitTest/901/

**Review by sfc-gh-jrose — APPROVED** [review]
Code looks good. 

nit: I'd prefer if the tests were parameterized so that each test case is considered a separate test.

**Review by sfc-gh-bolee — COMMENTED** [review]
Hi, I am not able to understand the code line by line, but just looked at the test cases and it looks good to me. One question though: There are some restrictions on the as of join sql, like match_condition can only have >=, >, <= and < operators, on clause of asof join can have conjuction of equi conditions or so. Will these be relying on the SQL engine? Can we have tests for these cases?

**Comment by sfc-gh-aalam** [comment]
> There are some restrictions on the as of join sql, like match_condition can only have >=, >, <= and < operators, on clause of asof join can have conjuction of equi conditions or so. Will these be relying on the SQL engine?

We will rely on sql engine to throw errors for these cases.

> Can we have tests for these cases?

Sure. I'll add tests for them

**Review by sfc-gh-bolee — APPROVED** [review]
LGTM. Thank you. (Not an expert for the code. only reviewed in high level)

**Pull request merged**
