### PR TITLE
SNOW-1757892: Improve Dataframe.print_schema for structured types

### PR DESCRIPTION
**Pull request by sfc-gh-jrose**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1757892

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.
   - [x] I acknowledge that I have ensured my changes to be thread-safe. Follow the link for more information: [Thread-safe Developer Guidelines](https://docs.google.com/document/d/162d_i4zZ2AfcGRXojj0jByt8EUq-DrSHPPnTa4QvwbA/edit#bookmark=id.e82u4nekq80k)

3. Please describe how your code solves the related issue.

   This PR adds support to DataFrame.print_schema for nested data types. Before this change a nested schema would be printed like so:
```
root
 |-- "MAP": MapType(StringType(), ArrayType(StructType([StructField('FIELD1', StringType(), nullable=True), StructField('FIELD2', LongType(), nullable=True)]))) (nullable = True)
```

After the change the nested schema will instead look like this:
```
root
 |-- "MAP": MapType (nullable = True)
 |   |-- key: StringType()
 |   |-- value: ArrayType
 |   |   |-- element: StructType
 |   |   |   |-- "FIELD1": StringType() (nullable = True)
 |   |   |   |-- "FIELD2": LongType() (nullable = True)
```

### CODE REVIEW

**Review by sfc-gh-jdu — APPROVED** [review]

**Review by sfc-gh-aalam — APPROVED** [review]

**Comment by sfc-gh-wshangguan** [comment]
Hi @sfc-gh-jrose , this definitely improves the behavior. But still some pointes to note
1. can we return the string instead of only printing it?
2. In my local test, seems like every time I try to pass in nested structure like `Array<Array<Integer>>`, the returned dataframe only gives me `Array<String>` type, which doesn't align with the example in this PR description. Am I missing anything?
3. Can we support accepting a parameter, which indicates the printed column name? Basically takes in new column names and print_schema with them.

**Comment by sfc-gh-jrose** [comment]
@sfc-gh-wshangguan 
1. We could add a utility method for that. Nobody has submitted a feature request for that yet.
2. Structured type support has not been rolled out yet. The Snowflake api always sends Snowpark semi-structured data. What you're seeing with `Array<String>` is the api returning structured data as json encoded strings.
3. I believe this use-case would be supported by a statement like `df.select(<columns>).print_schema()`.

**Comment by sfc-gh-wshangguan** [comment]
@sfc-gh-jrose 
Thanks for the explanation!
1. Yeah, this would be helpful for accelerated spark api project
2. Gotcha.
3. Right, that would be the common use case. What I was talking about is that for spark api project, we have a sort of column naming mapping between spark df and snowpark df. This means the column names in snowpark df print schema are inconsistent with spark df column name. If we can accept an optional parameter in print_schema, which replaces the default column names in print_schema, that can solve the problem.

**Comment by sfc-gh-wshangguan** [comment]
One more request is that we would need the level parameter similar to what spark df has in https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.printSchema.html

**Pull request merged**
