### PR TITLE
SNOW-1620446: add timedelta integration tests and notebooks

### PR DESCRIPTION
**Pull request by sfc-gh-lmukhopadhyay**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1620446

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.

3. Please describe how your code solves the related issue.

Adding notebooks with timedelta usecases and negative integration tests

### CODE REVIEW

**Comment by sfc-gh-evandenberg** [comment]
Are there any positive tests here?

**Comment by sfc-gh-nkrishna** [comment]
@sfc-gh-lmukhopadhyay Binary op subtraction (datetime - datetime = timedelta) was merged recently. Can you ensure this is part of the tests in this PR?

**Review by sfc-gh-azhan — COMMENTED** [review]
Is there a readme describe how to run notebook tests locally? Like how to setup the credentials for example?

**Comment by sfc-gh-lmukhopadhyay** [comment]
> Are there any positive tests here?

@sfc-gh-evandenberg The notebooks have some positive tests, but the idea is to re-enable the negative tests in test_timedelta_ops.py and undo the commented cells in the notebooks once all Timedelta operations are implemented, as outlined in this ticket [here](https://snowflakecomputing.atlassian.net/browse/SNOW-1635620)

**Comment by sfc-gh-azhan** [comment]
> > Is there a readme describe how to run notebook tests locally? Like how to setup the credentials for example?
> 
> @sfc-gh-azhan The credentials should already be setup, provided you've populated your tests.parameters file with CONNECTION_PARAMETERS. The notebooks can then be run by running `jupyter notebook` in this repo and opening the notebook files to run the cells. All the notebooks can also be run automatically via `python -m pytest -ra --nbmake --nbmake-timeout=1000 tests/notebooks/modin` which is how the daily notebook test is run. There isn't a readme for this yet but I can add one if it'd needed.

Please add one in the notebook test folder thanks!

**Review by sfc-gh-azhan — APPROVED** [review]

**Comment by sfc-gh-lmukhopadhyay** [comment]
> @sfc-gh-lmukhopadhyay Binary op subtraction (datetime - datetime = timedelta) was merged recently. Can you ensure this is part of the tests in this PR?

@sfc-gh-nkrishna This case should be in the MIMIC nb but is also explicitly in TimeSeriesTesting.ipynb now

**Review by sfc-gh-nkrishna — APPROVED** [review]

**Pull request merged**
