### PR TITLE
SNOW-1842464 Fix the stored procedure build break 

### PR DESCRIPTION
**Pull request by sfc-gh-oplaton**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1842464

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [x] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.
   - [x] I acknowledge that I have ensured my changes to be thread-safe. Follow the link for more information: [Thread-safe Developer Guidelines](https://github.com/snowflakedb/snowpark-python/blob/main/CONTRIBUTING.md#thread-safe-development)

3. Please describe how your code solves the related issue.

   Add explicit dependencies on `python-dateutil` to `setup.py` and `recipe/meta.yaml`.

### CODE REVIEW

**Comment by sfc-gh-aalam** [comment]
we also need to fix setup.py: https://ci-dev-142.int.snowflakecomputing.com/job/RT-Precommit-Tests/71/console

that fix is probably different and needs investigation.

**Review by sfc-gh-aalam — APPROVED** [review]

**Comment by sfc-gh-aalam** [comment]
I'm restarting https://ci-dev-142.int.snowflakecomputing.com/job/PythonStoredProcBuildPrecommitTest/1484/ since the failures could be due to branch name change

**Review by sfc-gh-azhan — COMMENTED** [review]
let's update changelog too.

**Comment by sfc-gh-oplaton** [comment]
> @sfc-gh-oplaton let's update changelog to say we are adding new dependency

Done.

**Comment by sfc-gh-oplaton** [comment]
> let's update changelog too.

Done.

**Review by sfc-gh-azhan — APPROVED** [review]

**Pull request merged**
