### PR TITLE
SNOW-1791556: Use docstrings folder for Index methods and properties

### PR DESCRIPTION
**Pull request by sfc-gh-helmeleegy**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1791556

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.
   - [ ] I acknowledge that I have ensured my changes to be thread-safe. Follow the link for more information: [Thread-safe Developer Guidelines](https://docs.google.com/document/d/162d_i4zZ2AfcGRXojj0jByt8EUq-DrSHPPnTa4QvwbA/edit#bookmark=id.e82u4nekq80k)

3. Please describe how your code solves the related issue.

   Use docstrings folder for Index methods and properties. Docstrings for DatetimeIndex and TimedeltaIndex will be treated similarly in follow-up PRs.

### CODE REVIEW

**Comment by sfc-gh-helmeleegy** [comment]
@sfc-gh-joshi @sfc-gh-mvashishtha I've started moving the docstrings for Index objects to the `docstrings` folder. Can you please take a look at this first PR?

**Review by sfc-gh-mvashishtha — COMMENTED** [review]
@sfc-gh-helmeleegy could you generate all the docs and check whether there are any diffs?

The code changes LGTM.

**Review by sfc-gh-joshi — APPROVED** [review]
LGTM, thanks! Please also check the doc HTML output like @sfc-gh-mvashishtha said, and the output of `help(pd.Index.method)` for at least a few methods.

**Comment by sfc-gh-helmeleegy** [comment]
> @sfc-gh-helmeleegy could you generate all the docs and check whether there are any diffs?
> 
> The code changes LGTM.

Thanks, Mahesh. I compared the generated docs (before and after the change) and they look the same.

**Comment by sfc-gh-helmeleegy** [comment]
> LGTM, thanks! Please also check the doc HTML output like @sfc-gh-mvashishtha said, and the output of `help(pd.Index.method)` for at least a few methods.

Thanks, Jonathan. I ran `help(...)` on a few properties/methods before and after the change and they all were the same.

**Review by sfc-gh-mvashishtha — APPROVED** [review]

**Pull request merged**
