### PR TITLE
SNOW-1445381: Override docstrings for Series.str/Series.dt

### PR DESCRIPTION
**Pull request by sfc-gh-joshi**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1445381

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.

3. Please describe how your code solves the related issue.

This PR moves the docstrings of `StringMethods` and `DatetimeProperties` to use docstring overrides.

### CODE REVIEW

**Review by sfc-gh-helmeleegy — COMMENTED** [review]
Can we verify that the total number of doctests passing for string methods is the same before and after this change - just to make sure we did not miss anything by mistake?

**Comment by sfc-gh-joshi** [comment]
> Can we verify that the total number of doctests passing for string methods is the same before and after this change - just to make sure we did not miss anything by mistake?

Good idea.

On this PR (d5d02e), `pytest src/snowflake/snowpark/modin/pandas/series_utils.py -k StringMethods` runs 15 tests. Latest main (ed9b5b) also runs 15. I'll do the same check for DatetimeProperties once I fix them (seems like the doc plugin isn't properly overriding them).

**Comment by sfc-gh-helmeleegy** [comment]
> > Can we verify that the total number of doctests passing for string methods is the same before and after this change - just to make sure we did not miss anything by mistake?
> 
> Good idea.
> 
> On this PR (d5d02e), `pytest src/snowflake/snowpark/modin/pandas/series_utils.py -k StringMethods` runs 15 tests. Latest main (ed9b5b) also runs 15. I'll do the same check for DatetimeProperties once I fix them (seems like the doc plugin isn't properly overriding them).

Sounds good.

**Review by sfc-gh-helmeleegy — COMMENTED** [review]
LGTM - after addressing the DatatimeProperties issue.
Thanks for getting this done!

**Review by sfc-gh-helmeleegy — APPROVED** [review]

**Comment by sfc-gh-joshi** [comment]
DT properties should be fixed -- current PR and latest main both run 8 doctests.

**Review by sfc-gh-vbudati — APPROVED** [review]
Looks good to me, thanks Jonathan!

**Pull request merged**
