### PR TITLE
SNOW-1332287, SNOW-1332288: Fix flaky tests for skew & kurtosis functions

### PR DESCRIPTION
**Pull request by sfc-gh-mheimel**
Fixes a flaky tests issue for tests involving skew/kurtosis correctness. We [recently updated](https://github.com/snowflakedb/snowflake/pull/170876) the computation for skew/kurtosis in XP to fix an issue that could lead to catastrophic loss of precision for very large tables. This fix causes skew/kurtosis to produce slightly different results, even for smaller cases. Since the failing tests compares the results of skew/kurtosis computation to expected constants absolutely, even tiny differences can cause a failure.

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

Fixes SNOW-1332287 & SNOW-1332288.

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

Fixed by a) Updating the reference values for skew/kurtosis tests to match the new computation, b) Making sure that skew/kurtosis tests use approximate comparisons for correctness testing.

### CODE REVIEW

**Comment by sfc-gh-mheimel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-jdu** [comment]
BTW, test_kurtosis seems still failing, maybe because your skew & kurtosis function changes are not in production yet?

**Comment by sfc-gh-mheimel** [comment]
> BTW, test_kurtosis seems still failing, maybe because your skew & kurtosis function changes are not in production yet?

Yes, my changes will only be rolled out once 8.16 hits production (± later this week). So, this will fail until then - and the existing code will fail from then on.

I could reduce the floating point threshold of the test further to ensure it passes on both pre and post 8.16. Unsure what's the best way forward is here.

**Comment by sfc-gh-jdu** [comment]
> > BTW, test_kurtosis seems still failing, maybe because your skew & kurtosis function changes are not in production yet?
> 
> Yes, my changes will only be rolled out once 8.17 hits production (± later this week). So, this will fail until then - and the existing code will fail from then on.
> 
> I could reduce the floating point threshold of the test further to ensure it passes on both pre and post 8.17. Unsure what's the best way forward is here.

Can you merge this change it to branch  test-v1.14.0 first, which is pulled in regression test. Once 8.17 is in, we merge again to main branch.

**Comment by sfc-gh-jdu** [comment]
It seems ready for merging?

**Review by sfc-gh-azhan — APPROVED** [review]

**Pull request merged**
