### PR TITLE
SNOW-701257: Remove error log

### PR DESCRIPTION
**Pull request by sfc-gh-yixie**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #SNOW-701257

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Remove the code that logs en exception as an error.

### CODE REVIEW

**Review by sfc-gh-sfan — COMMENTED** [review]
Do we still have the log of failed query + exception after this change?

**Comment by sfc-gh-yixie** [comment]
> Do we still have the log of failed query + exception after this change?

Good question. I'm thinking of adding the problematic SQL to SnowparkSQLException so people can get the SQL from the exception. Simply removing the error log will make it harder to support because users only see errors but don't see the SQL.

**Review by sfc-gh-sfan — APPROVED** [review]
Yeah that would be ideal. Having access to the query text would be helpful in case query id is missing for whatever reason. Do you want to include it in this PR or create a JIRA to follow up on?

The change itself looks good and given the exception has the query id, most of the time we should have enough info for debugging.

**Comment by sfc-gh-jdu** [comment]
Should we have a parameter to control this? I feel logging error is still useful when running tests, so it can be default to false

**Pull request closed without merging**
