### PR TITLE
SNOW-1272098: Catch accidental print statements with flake8.

### PR DESCRIPTION
**Pull request by sfc-gh-mvashishtha**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes SNOW-1272098

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   If we run flake8 with flake8-print and we accidentally add a print statement in a PR, lint will fail and prevent us from merging the PR.

### CODE REVIEW

**Comment by sfc-gh-mvashishtha** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-mvashishtha** [comment]
recheck

**Review by sfc-gh-stan — APPROVED** [review]

**Review by sfc-gh-jrose — APPROVED** [review]

**Review by sfc-gh-yuwang — APPROVED** [review]
LGTM

**Comment by sfc-gh-mvashishtha** [comment]
Could an authorized user please merge this PR?

**Pull request merged**
