### PR TITLE
Merge a recent version of main into the phase 0 staging branch

### PR DESCRIPTION
**Pull request by sfc-gh-oplaton**
1. Which Jira issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   

   Fixes SNOW-1491199

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
      - [ ] If this test skips Local Testing mode, I'm requesting review from @snowflakedb/local-testing
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency
   - [ ] If this is a new feature/behavior, I'm adding the Local Testing parity changes.
   - [x] I acknowledge that I have ensured my changes to be thread-safe. Follow the link for more information: [Thread-safe Developer Guidelines](https://docs.google.com/document/d/162d_i4zZ2AfcGRXojj0jByt8EUq-DrSHPPnTa4QvwbA/edit#bookmark=id.e82u4nekq80k)

3. Please describe how your code solves the related issue.

Merge the contents of `main` as of PR 2596 (commit `d0eead29ef7e38c0d36aebf7829dd794de0ba1f3`, `Mon Nov 11 11:53:26 2024 -0800`) into `ls-SNOW-1491199-merge-phase0-server-side`.

### CODE REVIEW

**Comment by sfc-gh-lspiegelberg** [comment]
@sfc-gh-oplaton I would suggest let's merge https://github.com/snowflakedb/snowpark-python/pull/2588 first (which fixes all gates) - then we can focus on this branch and make sure all gates pass with the changes brought in through main?

**Review by sfc-gh-lspiegelberg — CHANGES_REQUESTED** [review]
Let's merge once we have all gates in CI green, i.e. there are import errors shown atm

https://github.com/snowflakedb/snowpark-python/actions/runs/11787984936/job/32834335205?pr=2606

**Comment by sfc-gh-lspiegelberg** [comment]
> Let's merge once we have all gates in CI green, i.e. there are import errors shown atm
> 
> https://github.com/snowflakedb/snowpark-python/actions/runs/11787984936/job/32834335205?pr=2606

has been merged. https://github.com/snowflakedb/snowpark-python/pull/2588

**Comment by sfc-gh-oplaton** [comment]
> > Let's merge once we have all gates in CI green, i.e. there are import errors shown atm
> > https://github.com/snowflakedb/snowpark-python/actions/runs/11787984936/job/32834335205?pr=2606
> 
> has been merged. #2588

Ack, will wait for PR 2588

**Review by sfc-gh-lspiegelberg — APPROVED** [review]
LGTM, let's merge.

**Pull request merged**
