### PR TITLE
SNOW-1314326 Add GitHub workflow/script to check PRs

### PR DESCRIPTION
**Pull request by sfc-gh-vbudati**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #1314326

2. Fill out the following pre-review checklist:

   - [ ] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding a new telemetry message
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

   Porting over this script. It should check whether a PR is too long, has too many comments, and if it has been open for too long.

### CODE REVIEW

**Comment by sfc-gh-vbudati** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-vbudati** [comment]
recheck

**Comment by sfc-gh-joshi** [comment]
Where's the output of the workflow being sent? Is this purely informational?

**Comment by sfc-gh-vbudati** [comment]
I am pretty sure it's purely informational, I don't think it actually blocks anything. @sfc-gh-azhan can correct me if I am wrong.

**Comment by sfc-gh-yzou** [comment]
@sfc-gh-joshi @sfc-gh-vbudati yes, that is just daily job that checks all prs that is out to see if it violates any of our principle, manual check of outpput is required

**Review by sfc-gh-azhan — APPROVED** [review]

**Review by sfc-gh-nkrishna — APPROVED** [review]

**Review by sfc-gh-jdu — APPROVED** [review]

**Pull request merged**
